# Generated by Django 3.0.7 on 2020-06-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('image', models.ImageField(default='agents/default_agent.jpg', upload_to='agents/')),
            ],
        ),
    ]
