# Generated by Django 3.0.7 on 2020-06-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
