# Generated by Django 3.0.7 on 2020-06-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=150)),
                ('pr_location', models.CharField(default='null', max_length=50, null=True)),
                ('pr_type', models.CharField(choices=[('sale', 'Sale'), ('Rent', 'Rent')], max_length=50)),
                ('pr_price', models.PositiveIntegerField()),
                ('pr_area', models.PositiveIntegerField()),
                ('pr_beds', models.PositiveIntegerField()),
                ('pr_baths', models.PositiveIntegerField()),
                ('pr_garages', models.PositiveIntegerField()),
                ('pr_image', models.ImageField(default='property_images/default.png', upload_to='property_images/')),
            ],
        ),
    ]
