# Generated by Django 3.0.7 on 2020-06-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20200609_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='pr_area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='pr_baths',
            new_name='baths',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='pr_beds',
            new_name='beds',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='pr_garages',
            new_name='garages',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='pr_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='pr_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='pr_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='pr_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='pr_type',
            new_name='type',
        ),
    ]
