# Generated by Django 3.0.7 on 2020-06-09 09:54

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_ad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='ad_id',
        ),
        migrations.AddField(
            model_name='property',
            name='ads_id',
            field=models.CharField(default=properties.models.ads_keys, editable=False, max_length=8),
        ),
    ]
