# Generated by Django 3.0.7 on 2020-06-09 09:55

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20200609_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ads_id',
            field=models.CharField(default=properties.models.ads_keys, max_length=8),
        ),
    ]
