# Generated by Django 3.0.7 on 2020-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20200609_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
