# Generated by Django 3.0.7 on 2020-06-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20200609_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50),
        ),
    ]
