# Generated by Django 3.0.7 on 2020-06-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default='home/services_default.jpg', upload_to='home/'),
        ),
    ]
