# Generated by Django 3.0.7 on 2020-06-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_services_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='title',
        ),
    ]
